CREATE TABLE IF NOT EXISTS home (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS account (
    id SERIAL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS human (
    name VARCHAR(100) NULL,
    email VARCHAR(200) UNIQUE NOT NULL,
    password_salt CHAR(16) NOT NULL,
    password_hash BYTEA NOT NULL
) INHERITS (account);

CREATE TABLE IF NOT EXISTS account_in_home (
    account INTEGER REFERENCES account ON DELETE CASCADE NOT NULL,
    home INTEGER REFERENCES home ON DELETE CASCADE NOT NULL,
    PRIMARY KEY(account, home)
);

CREATE TABLE IF NOT EXISTS admin (
    account INTEGER REFERENCES account ON DELETE CASCADE NOT NULL,
    home INTEGER REFERENCES home ON DELETE CASCADE NOT NULL,
    PRIMARY KEY(account, home)
);

CREATE TABLE IF NOT EXISTS device (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    home INTEGER REFERENCES home ON DELETE CASCADE NOT NULL,
    UNIQUE(name, home)
) INHERITS (account);

CREATE TABLE IF NOT EXISTS api_key (
    key VARCHAR(32) PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    account INTEGER REFERENCES account ON DELETE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS alarm_clock (
    id SERIAL PRIMARY KEY,
    home INTEGER REFERENCES home ON DELETE CASCADE NOT NULL,
    name VARCHAR(100) NULL,
    enable_at TIMESTAMP WITH TIME ZONE NULL,
    UNIQUE(home, name)
);

CREATE TABLE IF NOT EXISTS alarm_clock_time (
    id SERIAL PRIMARY KEY,
    alarm_clock INTEGER REFERENCES alarm_clock NOT NULL,
    work_day_only BOOLEAN NOT NULL,
    non_work_day_only BOOLEAN NOT NULL,
    alarm_clock_time TIME NOT NULL,
    is_default BOOLEAN NOT NULL, -- Otherwise temporary
    valid_from TIMESTAMP WITH TIME ZONE NOT NULL,
    valid_to TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by INTEGER REFERENCES account NOT NULL
);