CREATE TABLE IF NOT EXISTS home (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS account (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NULL,
    email VARCHAR(200) UNIQUE NOT NULL,
    password_salt CHAR(16) NOT NULL,
    password_hash BYTEA NOT NULL
);

CREATE TABLE IF NOT EXISTS admin (
    account INTEGER REFERENCES account ON DELETE CASCADE NOT NULL ,
    home INTEGER REFERENCES home ON DELETE CASCADE NOT NULL ,
    PRIMARY KEY(account, home)
);

CREATE TABLE IF NOT EXISTS device (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    home INTEGER REFERENCES home ON DELETE CASCADE NOT NULL,
    UNIQUE(name, home)
);

CREATE TABLE IF NOT EXISTS api_key (
    key VARCHAR(32) PRIMARY KEY,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    account INTEGER REFERENCES account ON DELETE CASCADE,
    device INTEGER REFERENCES device ON DELETE CASCADE,
    CHECK ((account IS NULL) != (device IS NULL))
);